import { type NextPage } from "next";
import Head from "next/head";
import { InfoCard } from "@/components/info-card";
import { SignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { useGetMode } from "@/hooks/useGetMode";

const Home: NextPage = () => {
  const theme = useGetMode();
  return (
    <>
      <Head>
        <title>Tezzy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-gradient-to-tr from-slate-50  to-slate-300 dark:from-zinc-950">
        <SignedIn>
          <InfoCard />
        </SignedIn>
        <SignedOut>
          <SignIn
            appearance={{
              baseTheme: theme == "dark" ? dark : undefined,
              variables: {
                colorPrimary: "#0F172A",
              },
            }}
          />
        </SignedOut>
      </main>
    </>
  );
};

export default Home;
