import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { cn } from "@/lib/utils";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Tezzy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-gradient-to-tr from-slate-50 to-slate-300">
        <div>
          <Card className={cn("w-[380px]")}>
            <CardHeader>
              <CardTitle>
                <h1 className="text-6xl font-bold text-primary">Tezzy</h1>
              </CardTitle>
              <CardDescription>
                <p className="text-secondary-foreground">
                  Get started by editing <code>pages/index.tsx</code>
                </p>
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-secondary-foreground">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit,
                quos architecto! Facere repellendus quaerat eaque obcaecati!
                Vitae hic voluptatum vel, qui saepe non sed libero dolorem?
                Deserunt ipsam minus quae.
              </p>
            </CardContent>
            <CardFooter>
              <Button>Get Started</Button>
            </CardFooter>
          </Card>
        </div>
      </main>
    </>
  );
};

export default Home;
