import { type NextPage } from "next";
import Head from "next/head";
import { InfoCard } from "@/components/info-card";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tezzy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-gradient-to-tr from-slate-50  to-slate-300 dark:from-zinc-950">
        <InfoCard />
      </main>
    </>
  );
};

export default Home;
